WIP: Add backend support for sending custom acknowledgement messages
collective/collective.volto.formsupport pull request #24
Opened 2022-12-13 14:10 UTC by JeffersonBledsoe

See collective/collective.volto.formsupport#57 for more details

2023-05-23 23:59 UTC, JeffersonBledsoe commented
@cekk ready for review

2023-06-07 11:12 UTC, JeffersonBledsoe commented
@cekk Happy to merge this?

2023-06-12 07:52 UTC, cekk requested changes
What's the purpose of this pr? Send a message to the user that submitted the form?
Right now the email is only sent to the "owner" of the form, right (recipient field)?

LGTM but i think that you should do some additional things:

- update README to explain ne features
- update CHANGELOG (mentioning that this version need xxx version of the frontend)
-z (most important): upgrade-step that fix "send" field on already created blocks (from single string, to a list) or handle both use-case in the code to not break anything

2023-06-12 07:52 UTC, cekk commented on src/collective/volto/formsupport/restapi/services/submit_form/post.py
> +        if should_send:
Could be better to make this check before preparing the message? If not should_send you can return without doing anything..or not?

2023-12-15 12:09 UTC, JeffersonBledsoe commented
@cekk I've made all of the previously noted changes.

Unfortunately the frontend for this isn't merged or released yet. Would it be possible to have this PR merged so the functionality can be tested in the frontend, and then an additional PR made later before the next release to add documentation for the required frontend version for this feature?

2024-01-08 12:11 UTC, tiberiuichim approved these changes

2024-01-08 16:15 UTC, merged