Allow changing the format of the contents of the email
collective/collective.volto.formsupport pull request #31
Opened 2023-04-25 15:41 UTC by JeffersonBledsoe

Allow the email that is sent to either be styled as a list (current behaviour) or as a table (new behaviour from this PR)

2023-04-28 06:52 UTC, cekk requested changes

2023-04-28 06:52 UTC, cekk commented on src/collective/volto/formsupport/browser/send_mail_template_table.pt
> +    <caption i18n:translate="send_mail_text">Email results for ${title}</caption>
If i remember correctly, this should be write like this:

<caption i18n:translate="send_mail_text">Email results for <tal:title i18n:name="title">${title}</tal:title>

And then when you update locales, title will be dynamic

2023-04-28 06:52 UTC, cekk commented on src/collective/volto/formsupport/restapi/services/submit_form/post.py
> +            self.block.get("email_format", "")
probably better like this:

```
email_format = self.block.get("email_format", "")
template_name = self.email_format_page_template_mapping.get(email_format, "send_mail_template")
```

So you don't need to set a "" key in mapping dict

2023-04-28 06:52 UTC, cekk commented on src/collective/volto/formsupport/restapi/services/submit_form/post.py
> +        if not template_name:
This shouldn't be an option because we always have a default value

2023-05-22 14:22 UTC, JeffersonBledsoe commented
@cekk I made a few of the changes you brought up. Not sure if I should update the locales or if that's to be done as part of a release.

2023-05-23 21:16 UTC, cekk commented on src/collective/volto/formsupport/restapi/services/submit_form/post.py
> +        if not template_name:
I mean something like this:

```suggestion
 email_format_page_template_mapping = {
        "list": "send_mail_template",
        "table": "send_mail_template_table",
    }
 
 ...
 
 email_format = self.block.get("email_format", "")
 template_name = self.email_format_page_template_mapping.get(email_format, 'send_mail_template')
 
```

In this case you always have a default value (send_mail_template)

2023-05-23 21:17 UTC, cekk commented
> @cekk I made a few of the changes you brought up. Not sure if I should update the locales or if that's to be done as part of a release.

Yes, feel free to update locales to add new translations.

2023-05-24 00:37 UTC, JeffersonBledsoe commented
@cekk Thanks for checking over this again. I've updated the locales now too

2023-05-24 09:35 UTC, cekk commented
yes, will release with all the changes

2023-05-24 09:35 UTC, merged