Form Add Event
collective/collective.volto.formsupport pull request #73
Opened 2024-10-23 09:08 UTC by folix-01

- Form Add Event
- Form Data Adapter

Basically these features are needed to predispose the current addon to be customizable

2024-11-13 14:16 UTC, mamico approved these changes

2024-11-13 15:55 UTC, cekk requested changes

2024-11-13 16:57 UTC, mamico commented on CHANGES.rst
> +3.2.0 (unreleased)
@folix-01 I've "expanded" mine, can you do the same for your two points in the changelog?

2024-11-15 10:38 UTC, cekk approved these changes

2024-11-15 14:36 UTC, merged